### ISSUE TITLE
setting up a local environment fails at the migration step

### ISSUE THREAD

**Issue by codersquid** [pyohio/pyohio#68]
I'm trying to stand up the site locally, and migrate fails to run due to mailer throwing an error. From the stacktrace, I'm wondering if the requirements inadventerently pulled in a version of something that expects native migrations.

```
(venv) codersquid@pyohio ~/dev/conferences/pyohio (master*) 
» ./manage.py migrate mailer
Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
    utility.execute()
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
    output = self.handle(*args, **options)
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/management/commands/migrate.py", line 111, in handle
    ignore_ghosts = ignore_ghosts,
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/__init__.py", line 173, in migrate_app
    Migrations.calculate_dependencies()
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 229, in calculate_dependencies
    migration.calculate_dependencies()
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 363, in calculate_dependencies
    for migration in self._get_dependency_objects("depends_on"):
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 343, in _get_dependency_objects
    for app, name in getattr(self.migration_class(), attrname, []):
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 315, in migration_class
    return self.migration().Migration
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/utils/__init__.py", line 62, in method
    value = function(self)
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 304, in migration
    raise exceptions.UnknownMigration(self, sys.exc_info())
south.exceptions.UnknownMigration: Migration 'mailer:0001_initial' probably doesn't exist.
Traceback (most recent call last):
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/south/migration/base.py", line 302, in migration
    migration = __import__(full_name, {}, {}, ['Migration'])
  File "/home/codersquid/dev/conferences/pyohio/venv/local/lib/python2.7/site-packages/mailer/migrations/0001_initial.py", line 4, in <module>
    from django.db import models, migrations
ImportError: cannot import name migrations
```

My virtualenv was populated with `pip install on -r requirements/base.txt`. I installed pipdeptree so you can see my dependency tree.

Is this similar to what you have in production?

```
django-mailer==1.1
  - Django [required: >=1.4, installed: 1.6.2]
  - lockfile [required: >=0.8, installed: 0.12.2]
django-redis-cache==0.9.7
  - redis [required: >=2.4.5, installed: 2.7.2]
gondor==1.2.5
  - six [required: >=1.3.0, installed: 1.10.0]
gunicorn==0.17.2
hiredis==0.1.1
metron==0.1
pinax-theme-bootstrap==5.1.0
  - django-appconf [required: ==0.6, installed: 0.5]
  - django-bootstrap-form [required: >=3.0.0, installed: 3.1]
pinax-utils==1.0b1.dev3
pipdeptree==0.10.1
  - pip [required: >=6.0.0, installed: 9.0.1]
pkg-resources==0.0.0
psycopg2==2.4.6
setuptools==36.2.0
South==0.8.4
symposion==1.0b2.dev3
  - Django [required: >=1.5,<=1.6, installed: 1.6.2]
  - django-appconf [required: ==0.5, installed: 0.5]
  - django-forms-bootstrap [required: >=2.0.3.post2, installed: 3.0.0]
  - django-markitup [required: ==2.1, installed: 2.1]
  - django-model-utils [required: ==2.0.2, installed: 2.0.2]
    - Django [required: >=1.4.2, installed: 1.6.2]
  - django-reversion [required: ==1.8, installed: 1.8.0]
  - django-sitetree [required: ==1.0.0, installed: 1.0.0]
  - django-taggit [required: ==0.11.2, installed: 0.11.2]
  - django-timezones [required: ==0.2, installed: 0.2]
  - django-user-accounts [required: ==1.0b13, installed: 1.0b13]
    - django-appconf [required: ==0.5, installed: 0.5]
    - pytz [required: ==2012j, installed: 2012g]
  - easy-thumbnails [required: ==1.4, installed: 1.4]
    - django [required: >=1.4, installed: 1.6.2]
    - pillow [required: Any, installed: 2.3.0]
    - six [required: Any, installed: 1.10.0]
  - html5lib [required: ==0.95, installed: 0.95]
  - markdown [required: ==2.3.1, installed: 2.3.1]
wheel==0.30.0a0
```

**Comment by efloehr** [comment]
Yes, this is what we have in production, and we are also experiencing this issue with mailer.

**Comment by codersquid** [comment]
I checked, and migrations work with mail version 1.0.

Version 1.1, needs South >=1.0. You'd either need to move the south migration dirs to south_migrations or change SOUTH_MIGRATION_MODULES to point to the current directories.

Rather than suggesting that for current production, I think it would be better to make a new repo for future pyohios, and move this repo to pyohio-archive. For the new repo,upstream symposion which gives you the benefit of running Django > 1.6. That way you won't need the South migrations. Upstream is good at getting PRs in, if you need anything from the pyohio fork.

**Comment by codersquid** [comment]
fixed by https://github.com/pyohio/pyohio/commit/8a447c659b22103665e0c5b34dc4e468e94d3353
